apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-task
  labels:
    app: devops-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-task
  template:
    metadata:
      labels:
        app: devops-task
    spec:
      containers:
        - name: app
          image: samarthr8/devops-task:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

